services:
  web:
    image: ${REGISTRY:-docker.io}/nineaiyu/xadmin-web:${VERSION}
    container_name: xadmin-web
    hostname: xadmin-web
    ulimits:
      core: 0
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      HTTP_PORT: ${HTTP_PORT:-80}
      USE_LB: ${USE_LB:-1}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-4096m}
    ports:
      - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
    volumes:
      - ${VOLUME_DIR}/server/data:/data/xadmin/server/data
      - ${VOLUME_DIR}/nginx/data/logs:/var/log/nginx
    healthcheck:
      test: "curl -fsL http://localhost:51980/web/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - net