name: sync-image-mirror

on:
  push:
    tags:
      - 'v*'


jobs:
  sync_to_target_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prepare
        run: |
          wget -q  https://github.com/AliyunContainerService/image-syncer/releases/download/v1.5.5/image-syncer-v1.5.5-linux-amd64.tar.gz
          tar zxf image-syncer-v1.5.5-linux-amd64.tar.gz
          mv image-syncer /usr/local/bin/

      - name: start sync
        run: |
          TAG=$(basename ${GITHUB_REF})
          VERSION=${TAG/v/}
          cat <<EOF > auth.yml
          registry.cn-beijing.aliyuncs.com:
              username: ${{ secrets.ALIYUN_REGISTRY_USER }}
              password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
          EOF

          cat <<EOF > images.yml
          "docker.io/nineaiyu/xadmin-server:$｛VERSION｝": "registry.cn-beijing.aliyuncs.com/nineaiyu/xadmin-web:$｛VERSION｝"
          "docker.io/nineaiyu/xadmin-server:$｛VERSION｝": "registry.cn-beijing.aliyuncs.com/nineaiyu/xadmin-web:$｛VERSION｝"
          EOF
          image-syncer  --auth=./auth.yml --images=./images.yml
